[phases.setup]
packages = ["python312", "ffmpeg"]  # keep what you need

[phases.install]
commands = [
    "python3 -m ensurepip --upgrade",  # <-- install pip
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt"
]

[phases.start]
command = "uvicorn main:app --host 0.0.0.0 --port $PORT"